[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
definitions = { path = "crates/definitions" }
roma = { path = "crates/roma" }
lorenzo = { path = "crates/lorenzo" }

# serializetion
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4"
toml = "0.8"
ron = "0.8"

# misc
rand = { version = "0.8", features = ["std", "std_rng"] }
rustc-hash = "1.1.0"
