[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
definitions = { path = "crates/definitions" }
roma = { path = "crates/roma" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
rand = { version = "0.8", features = ["std", "std_rng"] }
rustc-hash = "1.1.0"
array2d = "0.3"
