[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
definitions.workspace = true
roma.workspace = true
serde.workspace = true
toml.workspace = true
rand.workspace = true
rustc-hash.workspace = true
array2d.workspace = true
rayon = "1.7"
itertools = "0.10"
