[package]
name = "roma"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
wgpu = "0.16"
pollster = "0.3"
cgmath = "0.18"
bytemuck = { version = "1.12", features = [ "derive" ] }
anyhow = "1.0"
winit_input_helper = "0.14"
lru = "0.10"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
