[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"

[dependencies.bincode]
git = "https://github.com/bincode-org/bincode.git"
tag = "v2.0.0-rc.3"
