[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
bincode.workspace = true
byteorder = "1.4.3"
rust-ini = "0.21"
serde_with.workspace = true
toml.workspace = true
ron.workspace = true
rustc-hash.workspace = true
