[package]
name = "assets-analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ao = { path = "../../../ao-rs" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
