name: ci

on:
  pull_request:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustc-codegen-cranelift-preview
      - name: cargo clippy
        run: cargo clippy --workspace
      - name: cargo build
        run: cargo build
